// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2.proto

package via.sdj3.slaugtherhouse2.protobuf;

/**
 * Protobuf type {@code AnimalPartGrpc}
 */
public final class AnimalPartGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnimalPartGrpc)
    AnimalPartGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalPartGrpc.newBuilder() to construct.
  private AnimalPartGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalPartGrpc() {
    partName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnimalPartGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalPartGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            partId_ = input.readInt64();
            break;
          }
          case 17: {

            partWeight_ = input.readDouble();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            partName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaugtherhouse2.protobuf.Proto2.internal_static_AnimalPartGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaugtherhouse2.protobuf.Proto2.internal_static_AnimalPartGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.class, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder.class);
  }

  public static final int PART_ID_FIELD_NUMBER = 1;
  private long partId_;
  /**
   * <code>int64 part_id = 1;</code>
   * @return The partId.
   */
  @java.lang.Override
  public long getPartId() {
    return partId_;
  }

  public static final int PART_WEIGHT_FIELD_NUMBER = 2;
  private double partWeight_;
  /**
   * <code>double part_weight = 2;</code>
   * @return The partWeight.
   */
  @java.lang.Override
  public double getPartWeight() {
    return partWeight_;
  }

  public static final int PART_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object partName_;
  /**
   * <code>string part_name = 3;</code>
   * @return The partName.
   */
  @java.lang.Override
  public java.lang.String getPartName() {
    java.lang.Object ref = partName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partName_ = s;
      return s;
    }
  }
  /**
   * <code>string part_name = 3;</code>
   * @return The bytes for partName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartNameBytes() {
    java.lang.Object ref = partName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (partId_ != 0L) {
      output.writeInt64(1, partId_);
    }
    if (java.lang.Double.doubleToRawLongBits(partWeight_) != 0) {
      output.writeDouble(2, partWeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, partName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (partId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, partId_);
    }
    if (java.lang.Double.doubleToRawLongBits(partWeight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, partWeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, partName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc)) {
      return super.equals(obj);
    }
    via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc other = (via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc) obj;

    if (getPartId()
        != other.getPartId()) return false;
    if (java.lang.Double.doubleToLongBits(getPartWeight())
        != java.lang.Double.doubleToLongBits(
            other.getPartWeight())) return false;
    if (!getPartName()
        .equals(other.getPartName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PART_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPartId());
    hash = (37 * hash) + PART_WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPartWeight()));
    hash = (37 * hash) + PART_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPartName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnimalPartGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnimalPartGrpc)
      via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaugtherhouse2.protobuf.Proto2.internal_static_AnimalPartGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaugtherhouse2.protobuf.Proto2.internal_static_AnimalPartGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.class, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder.class);
    }

    // Construct using via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      partId_ = 0L;

      partWeight_ = 0D;

      partName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaugtherhouse2.protobuf.Proto2.internal_static_AnimalPartGrpc_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc getDefaultInstanceForType() {
      return via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc build() {
      via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc buildPartial() {
      via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc result = new via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc(this);
      result.partId_ = partId_;
      result.partWeight_ = partWeight_;
      result.partName_ = partName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc) {
        return mergeFrom((via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc other) {
      if (other == via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.getDefaultInstance()) return this;
      if (other.getPartId() != 0L) {
        setPartId(other.getPartId());
      }
      if (other.getPartWeight() != 0D) {
        setPartWeight(other.getPartWeight());
      }
      if (!other.getPartName().isEmpty()) {
        partName_ = other.partName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long partId_ ;
    /**
     * <code>int64 part_id = 1;</code>
     * @return The partId.
     */
    @java.lang.Override
    public long getPartId() {
      return partId_;
    }
    /**
     * <code>int64 part_id = 1;</code>
     * @param value The partId to set.
     * @return This builder for chaining.
     */
    public Builder setPartId(long value) {
      
      partId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 part_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartId() {
      
      partId_ = 0L;
      onChanged();
      return this;
    }

    private double partWeight_ ;
    /**
     * <code>double part_weight = 2;</code>
     * @return The partWeight.
     */
    @java.lang.Override
    public double getPartWeight() {
      return partWeight_;
    }
    /**
     * <code>double part_weight = 2;</code>
     * @param value The partWeight to set.
     * @return This builder for chaining.
     */
    public Builder setPartWeight(double value) {
      
      partWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double part_weight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartWeight() {
      
      partWeight_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object partName_ = "";
    /**
     * <code>string part_name = 3;</code>
     * @return The partName.
     */
    public java.lang.String getPartName() {
      java.lang.Object ref = partName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string part_name = 3;</code>
     * @return The bytes for partName.
     */
    public com.google.protobuf.ByteString
        getPartNameBytes() {
      java.lang.Object ref = partName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string part_name = 3;</code>
     * @param value The partName to set.
     * @return This builder for chaining.
     */
    public Builder setPartName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string part_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartName() {
      
      partName_ = getDefaultInstance().getPartName();
      onChanged();
      return this;
    }
    /**
     * <code>string part_name = 3;</code>
     * @param value The bytes for partName to set.
     * @return This builder for chaining.
     */
    public Builder setPartNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnimalPartGrpc)
  }

  // @@protoc_insertion_point(class_scope:AnimalPartGrpc)
  private static final via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc();
  }

  public static via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalPartGrpc>
      PARSER = new com.google.protobuf.AbstractParser<AnimalPartGrpc>() {
    @java.lang.Override
    public AnimalPartGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalPartGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalPartGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalPartGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

