// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2.proto

package via.sdj3.slaugtherhouse2.protobuf;

public interface ProductGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>string product_type = 2;</code>
   * @return The productType.
   */
  java.lang.String getProductType();
  /**
   * <code>string product_type = 2;</code>
   * @return The bytes for productType.
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();
}
