// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package via.sdj3.slaughterhouse_v2.protobuf;

public interface AnimalIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 animal_id = 1;</code>
   * @return The animalId.
   */
  long getAnimalId();
}
