// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package via.sdj3.slaughterhouse_v2.protobuf;

public interface ProductIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();
}
