// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2.proto

package via.sdj3.slaughterhouse2.protobuf;

/**
 * Protobuf type {@code AnimalGrpc}
 */
public final class AnimalGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnimalGrpc)
    AnimalGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalGrpc.newBuilder() to construct.
  private AnimalGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalGrpc() {
    animalName_ = "";
    animalType_ = "";
    origin_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnimalGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            registrationNumber_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            animalName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            animalType_ = s;
            break;
          }
          case 33: {

            weight_ = input.readDouble();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            origin_ = s;
            break;
          }
          case 50: {
            via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.Builder subBuilder = null;
            if (registrationDate_ != null) {
              subBuilder = registrationDate_.toBuilder();
            }
            registrationDate_ = input.readMessage(via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(registrationDate_);
              registrationDate_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaughterhouse2.protobuf.Proto2.internal_static_AnimalGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaughterhouse2.protobuf.Proto2.internal_static_AnimalGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.class, via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.Builder.class);
  }

  public static final int REGISTRATION_NUMBER_FIELD_NUMBER = 1;
  private long registrationNumber_;
  /**
   * <code>int64 registration_number = 1;</code>
   * @return The registrationNumber.
   */
  @java.lang.Override
  public long getRegistrationNumber() {
    return registrationNumber_;
  }

  public static final int ANIMAL_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object animalName_;
  /**
   * <code>string animal_name = 2;</code>
   * @return The animalName.
   */
  @java.lang.Override
  public java.lang.String getAnimalName() {
    java.lang.Object ref = animalName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      animalName_ = s;
      return s;
    }
  }
  /**
   * <code>string animal_name = 2;</code>
   * @return The bytes for animalName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAnimalNameBytes() {
    java.lang.Object ref = animalName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      animalName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANIMAL_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object animalType_;
  /**
   * <code>string animal_type = 3;</code>
   * @return The animalType.
   */
  @java.lang.Override
  public java.lang.String getAnimalType() {
    java.lang.Object ref = animalType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      animalType_ = s;
      return s;
    }
  }
  /**
   * <code>string animal_type = 3;</code>
   * @return The bytes for animalType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAnimalTypeBytes() {
    java.lang.Object ref = animalType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      animalType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_FIELD_NUMBER = 4;
  private double weight_;
  /**
   * <code>double weight = 4;</code>
   * @return The weight.
   */
  @java.lang.Override
  public double getWeight() {
    return weight_;
  }

  public static final int ORIGIN_FIELD_NUMBER = 5;
  private volatile java.lang.Object origin_;
  /**
   * <code>string origin = 5;</code>
   * @return The origin.
   */
  @java.lang.Override
  public java.lang.String getOrigin() {
    java.lang.Object ref = origin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      origin_ = s;
      return s;
    }
  }
  /**
   * <code>string origin = 5;</code>
   * @return The bytes for origin.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginBytes() {
    java.lang.Object ref = origin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      origin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTRATION_DATE_FIELD_NUMBER = 6;
  private via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc registrationDate_;
  /**
   * <code>.LocalDateGrpc registration_date = 6;</code>
   * @return Whether the registrationDate field is set.
   */
  @java.lang.Override
  public boolean hasRegistrationDate() {
    return registrationDate_ != null;
  }
  /**
   * <code>.LocalDateGrpc registration_date = 6;</code>
   * @return The registrationDate.
   */
  @java.lang.Override
  public via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc getRegistrationDate() {
    return registrationDate_ == null ? via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.getDefaultInstance() : registrationDate_;
  }
  /**
   * <code>.LocalDateGrpc registration_date = 6;</code>
   */
  @java.lang.Override
  public via.sdj3.slaughterhouse2.protobuf.LocalDateGrpcOrBuilder getRegistrationDateOrBuilder() {
    return getRegistrationDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (registrationNumber_ != 0L) {
      output.writeInt64(1, registrationNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animalName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, animalName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animalType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, animalType_);
    }
    if (java.lang.Double.doubleToRawLongBits(weight_) != 0) {
      output.writeDouble(4, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(origin_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, origin_);
    }
    if (registrationDate_ != null) {
      output.writeMessage(6, getRegistrationDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (registrationNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, registrationNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animalName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, animalName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animalType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, animalType_);
    }
    if (java.lang.Double.doubleToRawLongBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(origin_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, origin_);
    }
    if (registrationDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRegistrationDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaughterhouse2.protobuf.AnimalGrpc)) {
      return super.equals(obj);
    }
    via.sdj3.slaughterhouse2.protobuf.AnimalGrpc other = (via.sdj3.slaughterhouse2.protobuf.AnimalGrpc) obj;

    if (getRegistrationNumber()
        != other.getRegistrationNumber()) return false;
    if (!getAnimalName()
        .equals(other.getAnimalName())) return false;
    if (!getAnimalType()
        .equals(other.getAnimalType())) return false;
    if (java.lang.Double.doubleToLongBits(getWeight())
        != java.lang.Double.doubleToLongBits(
            other.getWeight())) return false;
    if (!getOrigin()
        .equals(other.getOrigin())) return false;
    if (hasRegistrationDate() != other.hasRegistrationDate()) return false;
    if (hasRegistrationDate()) {
      if (!getRegistrationDate()
          .equals(other.getRegistrationDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGISTRATION_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRegistrationNumber());
    hash = (37 * hash) + ANIMAL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAnimalName().hashCode();
    hash = (37 * hash) + ANIMAL_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAnimalType().hashCode();
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeight()));
    hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
    hash = (53 * hash) + getOrigin().hashCode();
    if (hasRegistrationDate()) {
      hash = (37 * hash) + REGISTRATION_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaughterhouse2.protobuf.AnimalGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnimalGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnimalGrpc)
      via.sdj3.slaughterhouse2.protobuf.AnimalGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaughterhouse2.protobuf.Proto2.internal_static_AnimalGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaughterhouse2.protobuf.Proto2.internal_static_AnimalGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.class, via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.Builder.class);
    }

    // Construct using via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      registrationNumber_ = 0L;

      animalName_ = "";

      animalType_ = "";

      weight_ = 0D;

      origin_ = "";

      if (registrationDateBuilder_ == null) {
        registrationDate_ = null;
      } else {
        registrationDate_ = null;
        registrationDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaughterhouse2.protobuf.Proto2.internal_static_AnimalGrpc_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaughterhouse2.protobuf.AnimalGrpc getDefaultInstanceForType() {
      return via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaughterhouse2.protobuf.AnimalGrpc build() {
      via.sdj3.slaughterhouse2.protobuf.AnimalGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaughterhouse2.protobuf.AnimalGrpc buildPartial() {
      via.sdj3.slaughterhouse2.protobuf.AnimalGrpc result = new via.sdj3.slaughterhouse2.protobuf.AnimalGrpc(this);
      result.registrationNumber_ = registrationNumber_;
      result.animalName_ = animalName_;
      result.animalType_ = animalType_;
      result.weight_ = weight_;
      result.origin_ = origin_;
      if (registrationDateBuilder_ == null) {
        result.registrationDate_ = registrationDate_;
      } else {
        result.registrationDate_ = registrationDateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaughterhouse2.protobuf.AnimalGrpc) {
        return mergeFrom((via.sdj3.slaughterhouse2.protobuf.AnimalGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaughterhouse2.protobuf.AnimalGrpc other) {
      if (other == via.sdj3.slaughterhouse2.protobuf.AnimalGrpc.getDefaultInstance()) return this;
      if (other.getRegistrationNumber() != 0L) {
        setRegistrationNumber(other.getRegistrationNumber());
      }
      if (!other.getAnimalName().isEmpty()) {
        animalName_ = other.animalName_;
        onChanged();
      }
      if (!other.getAnimalType().isEmpty()) {
        animalType_ = other.animalType_;
        onChanged();
      }
      if (other.getWeight() != 0D) {
        setWeight(other.getWeight());
      }
      if (!other.getOrigin().isEmpty()) {
        origin_ = other.origin_;
        onChanged();
      }
      if (other.hasRegistrationDate()) {
        mergeRegistrationDate(other.getRegistrationDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaughterhouse2.protobuf.AnimalGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaughterhouse2.protobuf.AnimalGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long registrationNumber_ ;
    /**
     * <code>int64 registration_number = 1;</code>
     * @return The registrationNumber.
     */
    @java.lang.Override
    public long getRegistrationNumber() {
      return registrationNumber_;
    }
    /**
     * <code>int64 registration_number = 1;</code>
     * @param value The registrationNumber to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationNumber(long value) {
      
      registrationNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 registration_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationNumber() {
      
      registrationNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object animalName_ = "";
    /**
     * <code>string animal_name = 2;</code>
     * @return The animalName.
     */
    public java.lang.String getAnimalName() {
      java.lang.Object ref = animalName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animalName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string animal_name = 2;</code>
     * @return The bytes for animalName.
     */
    public com.google.protobuf.ByteString
        getAnimalNameBytes() {
      java.lang.Object ref = animalName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string animal_name = 2;</code>
     * @param value The animalName to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      animalName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string animal_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalName() {
      
      animalName_ = getDefaultInstance().getAnimalName();
      onChanged();
      return this;
    }
    /**
     * <code>string animal_name = 2;</code>
     * @param value The bytes for animalName to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      animalName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object animalType_ = "";
    /**
     * <code>string animal_type = 3;</code>
     * @return The animalType.
     */
    public java.lang.String getAnimalType() {
      java.lang.Object ref = animalType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animalType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string animal_type = 3;</code>
     * @return The bytes for animalType.
     */
    public com.google.protobuf.ByteString
        getAnimalTypeBytes() {
      java.lang.Object ref = animalType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animalType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string animal_type = 3;</code>
     * @param value The animalType to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      animalType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string animal_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalType() {
      
      animalType_ = getDefaultInstance().getAnimalType();
      onChanged();
      return this;
    }
    /**
     * <code>string animal_type = 3;</code>
     * @param value The bytes for animalType to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      animalType_ = value;
      onChanged();
      return this;
    }

    private double weight_ ;
    /**
     * <code>double weight = 4;</code>
     * @return The weight.
     */
    @java.lang.Override
    public double getWeight() {
      return weight_;
    }
    /**
     * <code>double weight = 4;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(double value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double weight = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object origin_ = "";
    /**
     * <code>string origin = 5;</code>
     * @return The origin.
     */
    public java.lang.String getOrigin() {
      java.lang.Object ref = origin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        origin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string origin = 5;</code>
     * @return The bytes for origin.
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      java.lang.Object ref = origin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string origin = 5;</code>
     * @param value The origin to set.
     * @return This builder for chaining.
     */
    public Builder setOrigin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      origin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string origin = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigin() {
      
      origin_ = getDefaultInstance().getOrigin();
      onChanged();
      return this;
    }
    /**
     * <code>string origin = 5;</code>
     * @param value The bytes for origin to set.
     * @return This builder for chaining.
     */
    public Builder setOriginBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      origin_ = value;
      onChanged();
      return this;
    }

    private via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc registrationDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc, via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.Builder, via.sdj3.slaughterhouse2.protobuf.LocalDateGrpcOrBuilder> registrationDateBuilder_;
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     * @return Whether the registrationDate field is set.
     */
    public boolean hasRegistrationDate() {
      return registrationDateBuilder_ != null || registrationDate_ != null;
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     * @return The registrationDate.
     */
    public via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc getRegistrationDate() {
      if (registrationDateBuilder_ == null) {
        return registrationDate_ == null ? via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.getDefaultInstance() : registrationDate_;
      } else {
        return registrationDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    public Builder setRegistrationDate(via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc value) {
      if (registrationDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        registrationDate_ = value;
        onChanged();
      } else {
        registrationDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    public Builder setRegistrationDate(
        via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.Builder builderForValue) {
      if (registrationDateBuilder_ == null) {
        registrationDate_ = builderForValue.build();
        onChanged();
      } else {
        registrationDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    public Builder mergeRegistrationDate(via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc value) {
      if (registrationDateBuilder_ == null) {
        if (registrationDate_ != null) {
          registrationDate_ =
            via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.newBuilder(registrationDate_).mergeFrom(value).buildPartial();
        } else {
          registrationDate_ = value;
        }
        onChanged();
      } else {
        registrationDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    public Builder clearRegistrationDate() {
      if (registrationDateBuilder_ == null) {
        registrationDate_ = null;
        onChanged();
      } else {
        registrationDate_ = null;
        registrationDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    public via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.Builder getRegistrationDateBuilder() {
      
      onChanged();
      return getRegistrationDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    public via.sdj3.slaughterhouse2.protobuf.LocalDateGrpcOrBuilder getRegistrationDateOrBuilder() {
      if (registrationDateBuilder_ != null) {
        return registrationDateBuilder_.getMessageOrBuilder();
      } else {
        return registrationDate_ == null ?
            via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.getDefaultInstance() : registrationDate_;
      }
    }
    /**
     * <code>.LocalDateGrpc registration_date = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc, via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.Builder, via.sdj3.slaughterhouse2.protobuf.LocalDateGrpcOrBuilder> 
        getRegistrationDateFieldBuilder() {
      if (registrationDateBuilder_ == null) {
        registrationDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc, via.sdj3.slaughterhouse2.protobuf.LocalDateGrpc.Builder, via.sdj3.slaughterhouse2.protobuf.LocalDateGrpcOrBuilder>(
                getRegistrationDate(),
                getParentForChildren(),
                isClean());
        registrationDate_ = null;
      }
      return registrationDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnimalGrpc)
  }

  // @@protoc_insertion_point(class_scope:AnimalGrpc)
  private static final via.sdj3.slaughterhouse2.protobuf.AnimalGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaughterhouse2.protobuf.AnimalGrpc();
  }

  public static via.sdj3.slaughterhouse2.protobuf.AnimalGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalGrpc>
      PARSER = new com.google.protobuf.AbstractParser<AnimalGrpc>() {
    @java.lang.Override
    public AnimalGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaughterhouse2.protobuf.AnimalGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

