// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2.proto

package via.sdj3.slaughterhouse2.protobuf;

public interface AnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalResponse)
    com.google.protobuf.MessageOrBuilder {
}
