// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2.proto

package via.sdj3.slaughterhouse2.protobuf;

public interface LocalDateGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocalDateGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 day = 1;</code>
   * @return The day.
   */
  int getDay();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 year = 3;</code>
   * @return The year.
   */
  int getYear();
}
