// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3.proto

package via.sdj3.slaugtherhouse2.protobuf;

public interface AnimalPartGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalPartGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 part_id = 1;</code>
   * @return The partId.
   */
  long getPartId();

  /**
   * <code>double part_weight = 2;</code>
   * @return The partWeight.
   */
  double getPartWeight();

  /**
   * <code>string part_name = 3;</code>
   * @return The partName.
   */
  java.lang.String getPartName();
  /**
   * <code>string part_name = 3;</code>
   * @return The bytes for partName.
   */
  com.google.protobuf.ByteString
      getPartNameBytes();
}
