// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto1.proto

package via.sdj3.slaugtherhouse2.protobuf;

public interface AnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalResponse)
    com.google.protobuf.MessageOrBuilder {
}
