// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3.proto

package via.sdj3.slaugtherhouse2.protobuf;

public interface TraysGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TraysGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TrayGrpc tray = 1;</code>
   */
  java.util.List<via.sdj3.slaugtherhouse2.protobuf.TrayGrpc> 
      getTrayList();
  /**
   * <code>repeated .TrayGrpc tray = 1;</code>
   */
  via.sdj3.slaugtherhouse2.protobuf.TrayGrpc getTray(int index);
  /**
   * <code>repeated .TrayGrpc tray = 1;</code>
   */
  int getTrayCount();
  /**
   * <code>repeated .TrayGrpc tray = 1;</code>
   */
  java.util.List<? extends via.sdj3.slaugtherhouse2.protobuf.TrayGrpcOrBuilder> 
      getTrayOrBuilderList();
  /**
   * <code>repeated .TrayGrpc tray = 1;</code>
   */
  via.sdj3.slaugtherhouse2.protobuf.TrayGrpcOrBuilder getTrayOrBuilder(
      int index);
}
