// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3.proto

package via.sdj3.slaugtherhouse2.protobuf;

public interface TrayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayResponse)
    com.google.protobuf.MessageOrBuilder {
}
