// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3.proto

package via.sdj3.slaugtherhouse2.protobuf;

public interface TrayGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrayGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tray_id = 1;</code>
   * @return The trayId.
   */
  long getTrayId();

  /**
   * <code>string part_type = 2;</code>
   * @return The partType.
   */
  java.lang.String getPartType();
  /**
   * <code>string part_type = 2;</code>
   * @return The bytes for partType.
   */
  com.google.protobuf.ByteString
      getPartTypeBytes();

  /**
   * <code>double max_weight = 3;</code>
   * @return The maxWeight.
   */
  double getMaxWeight();

  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  java.util.List<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc> 
      getPartsList();
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc getParts(int index);
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  java.util.List<? extends via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder getPartsOrBuilder(
      int index);
}
