// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3.proto

package via.sdj3.slaugtherhouse2.protobuf;

/**
 * Protobuf type {@code TrayGrpc}
 */
public final class TrayGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TrayGrpc)
    TrayGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrayGrpc.newBuilder() to construct.
  private TrayGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrayGrpc() {
    partType_ = "";
    parts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrayGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrayGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            trayId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            partType_ = s;
            break;
          }
          case 25: {

            maxWeight_ = input.readDouble();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              parts_ = new java.util.ArrayList<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc>();
              mutable_bitField0_ |= 0x00000001;
            }
            parts_.add(
                input.readMessage(via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        parts_ = java.util.Collections.unmodifiableList(parts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaugtherhouse2.protobuf.Proto3.internal_static_TrayGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaugtherhouse2.protobuf.Proto3.internal_static_TrayGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.class, via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.Builder.class);
  }

  public static final int TRAY_ID_FIELD_NUMBER = 1;
  private long trayId_;
  /**
   * <code>int64 tray_id = 1;</code>
   * @return The trayId.
   */
  @java.lang.Override
  public long getTrayId() {
    return trayId_;
  }

  public static final int PART_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object partType_;
  /**
   * <code>string part_type = 2;</code>
   * @return The partType.
   */
  @java.lang.Override
  public java.lang.String getPartType() {
    java.lang.Object ref = partType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partType_ = s;
      return s;
    }
  }
  /**
   * <code>string part_type = 2;</code>
   * @return The bytes for partType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartTypeBytes() {
    java.lang.Object ref = partType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_WEIGHT_FIELD_NUMBER = 3;
  private double maxWeight_;
  /**
   * <code>double max_weight = 3;</code>
   * @return The maxWeight.
   */
  @java.lang.Override
  public double getMaxWeight() {
    return maxWeight_;
  }

  public static final int PARTS_FIELD_NUMBER = 4;
  private java.util.List<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc> parts_;
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc> getPartsList() {
    return parts_;
  }
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder> 
      getPartsOrBuilderList() {
    return parts_;
  }
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  @java.lang.Override
  public int getPartsCount() {
    return parts_.size();
  }
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  @java.lang.Override
  public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc getParts(int index) {
    return parts_.get(index);
  }
  /**
   * <code>repeated .AnimalPartGrpc parts = 4;</code>
   */
  @java.lang.Override
  public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder getPartsOrBuilder(
      int index) {
    return parts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trayId_ != 0L) {
      output.writeInt64(1, trayId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, partType_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxWeight_) != 0) {
      output.writeDouble(3, maxWeight_);
    }
    for (int i = 0; i < parts_.size(); i++) {
      output.writeMessage(4, parts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trayId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, trayId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, partType_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxWeight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, maxWeight_);
    }
    for (int i = 0; i < parts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, parts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaugtherhouse2.protobuf.TrayGrpc)) {
      return super.equals(obj);
    }
    via.sdj3.slaugtherhouse2.protobuf.TrayGrpc other = (via.sdj3.slaugtherhouse2.protobuf.TrayGrpc) obj;

    if (getTrayId()
        != other.getTrayId()) return false;
    if (!getPartType()
        .equals(other.getPartType())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxWeight())
        != java.lang.Double.doubleToLongBits(
            other.getMaxWeight())) return false;
    if (!getPartsList()
        .equals(other.getPartsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTrayId());
    hash = (37 * hash) + PART_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPartType().hashCode();
    hash = (37 * hash) + MAX_WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxWeight()));
    if (getPartsCount() > 0) {
      hash = (37 * hash) + PARTS_FIELD_NUMBER;
      hash = (53 * hash) + getPartsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaugtherhouse2.protobuf.TrayGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TrayGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TrayGrpc)
      via.sdj3.slaugtherhouse2.protobuf.TrayGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaugtherhouse2.protobuf.Proto3.internal_static_TrayGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaugtherhouse2.protobuf.Proto3.internal_static_TrayGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.class, via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.Builder.class);
    }

    // Construct using via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPartsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      trayId_ = 0L;

      partType_ = "";

      maxWeight_ = 0D;

      if (partsBuilder_ == null) {
        parts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        partsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaugtherhouse2.protobuf.Proto3.internal_static_TrayGrpc_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaugtherhouse2.protobuf.TrayGrpc getDefaultInstanceForType() {
      return via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaugtherhouse2.protobuf.TrayGrpc build() {
      via.sdj3.slaugtherhouse2.protobuf.TrayGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaugtherhouse2.protobuf.TrayGrpc buildPartial() {
      via.sdj3.slaugtherhouse2.protobuf.TrayGrpc result = new via.sdj3.slaugtherhouse2.protobuf.TrayGrpc(this);
      int from_bitField0_ = bitField0_;
      result.trayId_ = trayId_;
      result.partType_ = partType_;
      result.maxWeight_ = maxWeight_;
      if (partsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          parts_ = java.util.Collections.unmodifiableList(parts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.parts_ = parts_;
      } else {
        result.parts_ = partsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaugtherhouse2.protobuf.TrayGrpc) {
        return mergeFrom((via.sdj3.slaugtherhouse2.protobuf.TrayGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaugtherhouse2.protobuf.TrayGrpc other) {
      if (other == via.sdj3.slaugtherhouse2.protobuf.TrayGrpc.getDefaultInstance()) return this;
      if (other.getTrayId() != 0L) {
        setTrayId(other.getTrayId());
      }
      if (!other.getPartType().isEmpty()) {
        partType_ = other.partType_;
        onChanged();
      }
      if (other.getMaxWeight() != 0D) {
        setMaxWeight(other.getMaxWeight());
      }
      if (partsBuilder_ == null) {
        if (!other.parts_.isEmpty()) {
          if (parts_.isEmpty()) {
            parts_ = other.parts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePartsIsMutable();
            parts_.addAll(other.parts_);
          }
          onChanged();
        }
      } else {
        if (!other.parts_.isEmpty()) {
          if (partsBuilder_.isEmpty()) {
            partsBuilder_.dispose();
            partsBuilder_ = null;
            parts_ = other.parts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            partsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartsFieldBuilder() : null;
          } else {
            partsBuilder_.addAllMessages(other.parts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaugtherhouse2.protobuf.TrayGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaugtherhouse2.protobuf.TrayGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long trayId_ ;
    /**
     * <code>int64 tray_id = 1;</code>
     * @return The trayId.
     */
    @java.lang.Override
    public long getTrayId() {
      return trayId_;
    }
    /**
     * <code>int64 tray_id = 1;</code>
     * @param value The trayId to set.
     * @return This builder for chaining.
     */
    public Builder setTrayId(long value) {
      
      trayId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tray_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayId() {
      
      trayId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object partType_ = "";
    /**
     * <code>string part_type = 2;</code>
     * @return The partType.
     */
    public java.lang.String getPartType() {
      java.lang.Object ref = partType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string part_type = 2;</code>
     * @return The bytes for partType.
     */
    public com.google.protobuf.ByteString
        getPartTypeBytes() {
      java.lang.Object ref = partType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string part_type = 2;</code>
     * @param value The partType to set.
     * @return This builder for chaining.
     */
    public Builder setPartType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string part_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartType() {
      
      partType_ = getDefaultInstance().getPartType();
      onChanged();
      return this;
    }
    /**
     * <code>string part_type = 2;</code>
     * @param value The bytes for partType to set.
     * @return This builder for chaining.
     */
    public Builder setPartTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partType_ = value;
      onChanged();
      return this;
    }

    private double maxWeight_ ;
    /**
     * <code>double max_weight = 3;</code>
     * @return The maxWeight.
     */
    @java.lang.Override
    public double getMaxWeight() {
      return maxWeight_;
    }
    /**
     * <code>double max_weight = 3;</code>
     * @param value The maxWeight to set.
     * @return This builder for chaining.
     */
    public Builder setMaxWeight(double value) {
      
      maxWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double max_weight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxWeight() {
      
      maxWeight_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc> parts_ =
      java.util.Collections.emptyList();
    private void ensurePartsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        parts_ = new java.util.ArrayList<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc>(parts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder> partsBuilder_;

    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public java.util.List<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc> getPartsList() {
      if (partsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parts_);
      } else {
        return partsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public int getPartsCount() {
      if (partsBuilder_ == null) {
        return parts_.size();
      } else {
        return partsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc getParts(int index) {
      if (partsBuilder_ == null) {
        return parts_.get(index);
      } else {
        return partsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder setParts(
        int index, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartsIsMutable();
        parts_.set(index, value);
        onChanged();
      } else {
        partsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder setParts(
        int index, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder builderForValue) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.set(index, builderForValue.build());
        onChanged();
      } else {
        partsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder addParts(via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartsIsMutable();
        parts_.add(value);
        onChanged();
      } else {
        partsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder addParts(
        int index, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartsIsMutable();
        parts_.add(index, value);
        onChanged();
      } else {
        partsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder addParts(
        via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder builderForValue) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.add(builderForValue.build());
        onChanged();
      } else {
        partsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder addParts(
        int index, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder builderForValue) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.add(index, builderForValue.build());
        onChanged();
      } else {
        partsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder addAllParts(
        java.lang.Iterable<? extends via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc> values) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parts_);
        onChanged();
      } else {
        partsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder clearParts() {
      if (partsBuilder_ == null) {
        parts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        partsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public Builder removeParts(int index) {
      if (partsBuilder_ == null) {
        ensurePartsIsMutable();
        parts_.remove(index);
        onChanged();
      } else {
        partsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder getPartsBuilder(
        int index) {
      return getPartsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder getPartsOrBuilder(
        int index) {
      if (partsBuilder_ == null) {
        return parts_.get(index);  } else {
        return partsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public java.util.List<? extends via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder> 
         getPartsOrBuilderList() {
      if (partsBuilder_ != null) {
        return partsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parts_);
      }
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder addPartsBuilder() {
      return getPartsFieldBuilder().addBuilder(
          via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.getDefaultInstance());
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder addPartsBuilder(
        int index) {
      return getPartsFieldBuilder().addBuilder(
          index, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.getDefaultInstance());
    }
    /**
     * <code>repeated .AnimalPartGrpc parts = 4;</code>
     */
    public java.util.List<via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder> 
         getPartsBuilderList() {
      return getPartsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder> 
        getPartsFieldBuilder() {
      if (partsBuilder_ == null) {
        partsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpc.Builder, via.sdj3.slaugtherhouse2.protobuf.AnimalPartGrpcOrBuilder>(
                parts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        parts_ = null;
      }
      return partsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TrayGrpc)
  }

  // @@protoc_insertion_point(class_scope:TrayGrpc)
  private static final via.sdj3.slaugtherhouse2.protobuf.TrayGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaugtherhouse2.protobuf.TrayGrpc();
  }

  public static via.sdj3.slaugtherhouse2.protobuf.TrayGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrayGrpc>
      PARSER = new com.google.protobuf.AbstractParser<TrayGrpc>() {
    @java.lang.Override
    public TrayGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrayGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrayGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrayGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaugtherhouse2.protobuf.TrayGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

